# NO WARRANTY. THIS DEFENSE INNOVATION UNIT MATERIAL MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING,
# BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE
# OF THE MATERIAL. THE DEFENSE INNOVATION UNIT DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM
# PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.

version: "3.9"

x-service-common: &service-common
  build: &service-common-build
    context: ../
    dockerfile: ./infrastructure/Dockerfile
    network: host
    args: &service-common-build-args
      BASE_DIR: .
      DEPLOYMENT: "${DEPLOYMENT:-development}"
      DEPLOY_DEVELOPMENT: "${DEVELOPMENT:-true}"
      DEPLOY_PRODUCTION: "${PRODUCTION:-false}"
      UPSTREAM_IMAGE_NAME: "${UPSTREAM_IMAGE_NAME:-jupyter/minimal-notebook}"
      UPSTREAM_IMAGE_TAG: "${UPSTREAM_IMAGE_TAG:-notebook-6.4.12}"
      BASE_IMAGE: "${UPSTREAM_IMAGE_NAME:-jupyter/minimal-notebook}:${UPSTREAM_IMAGE_TAG:-notebook-6.4.12}"
      BASE_USER: "${BASE_USER:-jovyan}"
  user: "${NB_USER:-jovyan}:${NB_GROUP:-users}"
  environment: &service-common-environment
    DIU_AMMO_HOME: "/home/jovyan/work"
    DIU_AMMO_DATA_DIR: "/home/jovyan/work/data"
    DIU_AMMO_NOTEBOOKS_DIR: "/home/jovyan/work/notebooks"
    DIU_AMMO_MODELS_DIR: "/home/jovyan/work/models"
  volumes:
    - "../resources/notebooks:/home/jovyan/work/notebooks"
  deploy: &service-common-deploy
    mode: global
    endpoint_mode: vip
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    update_config:
      parallelism: 2
      delay: 10s
      failure_action: continue
      monitor: 10s
      max_failure_ratio: 0.3
    resources:
      limits:
        cpus: "2.0"
        memory: 8G
      reservations:
        cpus: "1.0"
        memory: 2G
  sysctls:
    - net.ipv4.ip_forward=1

services:
  jupyter:
    <<: *service-common
    profiles: ["server"]
    build:
      <<: *service-common-build
      args:
        <<: *service-common-build-args
        BUILD_TARGET: "${BUILD_TARGET:-diu_ammo_production}"
        IMAGE_PREFIX: "${BASE_IMAGE_PREFIX:-diu}"
        IMAGE_NAMESPACE: "${IMAGE_NAMESPACE:-ammo}"
        IMAGE_TAG: "${IMAGE_TAG:-production}"
      target: "${BUILD_TARGET:-diu_ammo_production}"
    hostname: jupyter.ammo.diu
    runtime: nvidia
    image: "${IMAGE_PREFIX:-diu}/${IMAGE_NAMESPACE:-ammo}:${IMAGE_TAG:-production}"
    ports:
      - "65432:8888"
    environment:
      <<: *service-common-environment
      NVIDIA_REQUIRE_CUDA: "cuda>=11.0 driver>=450"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      <<: *service-common-deploy
      resources:
        limits:
          cpus: "4.0"
          memory: 16G
        reservations:
          cpus: "2.0"
          memory: 4G

